### PR TITLE
Add credit card forging

### PR DESCRIPTION
**Pull request by lfarmer**
As a result of the some of the work I'm doing at the moment, thought it would be good if Forgery could generate random, valid, credit card numbers.

### CODE REVIEW

**Comment by seize-the-dave** [comment]
Thanks Lea.  Nice work.

**Comment by lfarmer** [comment]
No probs, will try to add a bit more over the coming weeks

**Comment by dgunthor** [comment]
Nice job Fingers!

**Comment by seize-the-dave** [comment]
:hand: :open_hands: :raised_hands:

**Comment by lfarmer** [comment]
feeling the love :)

**Pull request merged**
